### PR TITLE
Cset02 mongo db setup

### PR DESCRIPTION
**Pull request by gartho33**
Mongo connections should work. A user will be printed in console should this be the case, otherwise please contact me.

### CODE REVIEW

**Comment by WayneMaree** [comment]
Looking good, but need to move the DB stuff to it's own file. So add a file in the config folder and link to it where it's needed. For future reference don't put anything directly in the server file.

**Comment by Vannilaknight** [comment]
Code looks good just we need it in the right places.

**Comment by jleininger** [comment]
@gartho33 - Make sure that the Mongo stuff gets moved into its own file that we can require into the server file. Also not sure why there is commented out code in the server.js file.

**Comment by gartho33** [comment]
Code is now ready for review, please contact me if you cannot/do not understand anything.

**Comment by jleininger** [comment]
@gartho33 - Going to go ahead and merge this, but I still not quite sure what exactly you are testing with your test file. It looks like you are just testing the functionality of mongoose and not any logic inside the functions themselves. Also, it looks like these tests are all chained together through callbacks. This is not a good practice, if one test fails, it will cause the ones connected to it to fail too or not run at all.

**Pull request merged**
